name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run: echo "My First Github Actions Job"

    - name: Checkout Code repo
      uses: actions/checkout@v4

    - name: List files & Read files
      run: |
        ls -ltr
        cat README.md
    
    - name: Generate ASCII Artwork
      run: cowsay -f dragon "Run for cover, I am a dragon......RAWR" >> dragon.txt
      
