name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run: echo "My First Github Actions Job"

    - name: Checkout Code repo
      uses: actions/checkout@v4

    - name: List files
      run: ls -ltr

    - name: Read file
      run: cat README.md
